### ISSUE TITLE
Incorrect number of packages

### ISSUE THREAD

**Issue by Misko-2083** [terminalforlife/lspkg#1]
I've noticed that the number of packages listed with lspkg doesn't mach the number of total packages installed.
```bash
./lspkg -c
...
lists of packages
...
TOTAL: 3,188
./lspkg --match-with=glob -c -n -N libxv* moc
libxv-dev
libxv1
libxvidcore4
libxvmc1

TOTAL: 4/3,188
```
Normally I would use these oneliners to count the packages
```bash
dpkg -l | grep -c ^ii
3329
dpkg-query -l | grep -c ^ii
3329
```

**Comment by terminalforlife** [comment]
Sorry I got to this so late. Only just realised it was there.

Thank you for pointing that out. I have been using lspkg a lot for a while and didn't realise there was an inconsistency. I just checked it on my end and I get 1461 from lspkg and 1478 by directly counting them like you did. I'll look into it, ASAP.
